// <auto-generated />
using System;
using FitnessCentar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCentar.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    partial class FitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCentar.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Age = 23,
                            FirstName = "Nikola",
                            Goal = "Muscle Gain",
                            LastName = "Jadzic",
                            MembershipStartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0601234567",
                            TrainerId = 1,
                            Weight = 82.5
                        },
                        new
                        {
                            ClientId = 2,
                            Age = 29,
                            FirstName = "Nikola",
                            Goal = "Weight Loss",
                            LastName = "Danicic",
                            MembershipStartDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0619876543",
                            TrainerId = 2,
                            Weight = 64.0
                        },
                        new
                        {
                            ClientId = 3,
                            Age = 31,
                            FirstName = "Dalibor",
                            Goal = "Conditioning",
                            LastName = "Vitorovic",
                            MembershipStartDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "062555444",
                            TrainerId = 3,
                            Weight = 91.200000000000003
                        });
                });

            modelBuilder.Entity("FitnessCentar.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = 1,
                            FirstName = "Filip",
                            LastName = "Komarica",
                            Specialization = "Strength Training",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            TrainerId = 2,
                            FirstName = "Jovana",
                            LastName = "Jokic",
                            Specialization = "Weight Loss",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            TrainerId = 3,
                            FirstName = "Nikola",
                            LastName = "Markovic",
                            Specialization = "Functional Training",
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("FitnessCentar.Models.Client", b =>
                {
                    b.HasOne("FitnessCentar.Models.Trainer", "Trainer")
                        .WithMany("Clients")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCentar.Models.Trainer", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
